### PR TITLE
[XTG-322] Game Section Re-Design - Edit Game Page Layout Updates

### PR DESCRIPTION
**Pull request by ramirlm**
- Fetch and fill out Achievements table
- Fetch and fill out Leaderboards
- Adds an extra column to show the leaderboard aside to Game Name and secrets when medium screens or below
image
- Small other improvements

The remaining work on XTG-198 will be created in different PRs for each subtask I've created (if not a problem :) )

### CODE REVIEW

**Comment by fredericobraga85** [comment]
image
Looks like there are some linting errors during deployment..

Apart from that, lgtm !

**Comment by ramirlm** [comment]
Fixed @fredericobraga85 ! Thankssss

**Comment by ccmoralesj** [comment]
We still have linting errors:
image

**Comment by ramirlm** [comment]
Sorry about it @ccmoralesj – fixed!

**Pull request merged**
